#### crowsnest.conf — Logitech C922 Pro

[crowsnest]
log_path: /home/pi/printer_data/logs/crowsnest.log
log_level: quiet
delete_log: true
no_proxy: false

[cam 1]
mode: ustreamer
port: 8080
device: /dev/video0
# resolution: 1280x720
resolution:             1920x1080
max_fps: 30
enable_rtsp: false
rtsp_port: 8554
v4l2ctl: focus_automatic_continuous=0,power_line_frequency=1

# #### crowsnest.conf — Logitech C922 Pro

# [crowsnest]
# log_path: /home/pi/printer_data/logs/crowsnest.log
# log_level: quiet
# delete_log: true
# no_proxy: false

# [cam 1]
# mode:                   ustreamer
# port:                   8080
# device:                 /dev/video0
# resolution:             1280x720
# max_fps:                60
# enable_rtsp:            false
# rtsp_port:              8554
# v4l2ctl:                focus_automatic_continuous=0,
#                         power_line_frequency=1,
#                         white_balance_automatic=0,
#                         white_balance_temperature=4500,
#                         auto_exposure=1,
#                         exposure_time_absolute=300,
#                         exposure_dynamic_framerate=0,
#                         brightness=128,
#                         contrast=128,
#                         saturation=128,
#                         sharpness=150,
#                         gain=0,
#                         backlight_compensation=0